services:
  api:
    build:
      context: .
      dockerfile: Dockerfile      
    image: api_integrator:latest # Nombre de la imagen
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    env_file:
      - .env
    command: ["npm", "run", "start"]
